from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from app.schemas.documentation import DocumentationSpecification


# Directory where generated PDF documents are stored.
PDF_OUTPUT_DIR = Path("generated_documents")
PDF_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)


def _build_styles():
    """
    Create reusable PDF paragraph styles.
    """

    styles = getSampleStyleSheet()

    return {
        "title": ParagraphStyle(
            "DocumentTitle",
            parent=styles["Title"],
            fontSize=24,
            leading=30,
            alignment=TA_CENTER,
            spaceAfter=12,
        ),
        "subtitle": ParagraphStyle(
            "DocumentSubtitle",
            parent=styles["Normal"],
            fontSize=10,
            leading=15,
            alignment=TA_CENTER,
            textColor=colors.HexColor("#667085"),
            spaceAfter=25,
        ),
        "heading": ParagraphStyle(
            "SectionHeading",
            parent=styles["Heading2"],
            fontSize=15,
            leading=20,
            spaceBefore=16,
            spaceAfter=8,
            textColor=colors.HexColor("#101828"),
        ),
        "body": ParagraphStyle(
            "BodyText",
            parent=styles["BodyText"],
            fontSize=10,
            leading=15,
            spaceAfter=8,
            textColor=colors.HexColor("#344054"),
        ),
        "bullet": ParagraphStyle(
            "BulletText",
            parent=styles["BodyText"],
            fontSize=10,
            leading=15,
            leftIndent=12,
            firstLineIndent=-8,
            spaceAfter=5,
            textColor=colors.HexColor("#344054"),
        ),
    }


def _add_section(
    story: list,
    heading: str,
    items: list[str],
    styles: dict,
) -> None:
    """
    Add a heading and bullet-list section to the PDF.
    """

    story.append(
        Paragraph(
            heading,
            styles["heading"],
        )
    )

    for item in items:
        story.append(
            Paragraph(
                f"• {item}",
                styles["bullet"],
            )
        )


def generate_documentation_pdf(
    documentation: DocumentationSpecification,
) -> Path:
    """
    Generate a professional client-facing PDF from the structured
    Documentation Agent output.

    Returns:
        Path: Path to the generated PDF file.
    """

    if documentation is None:
        raise ValueError(
            "Documentation specification is required."
        )

    safe_title = (
        documentation.project_title
        .strip()
        .replace("/", "-")
        .replace("\\", "-")
    )

    file_name = f"{safe_title}.pdf"
    output_path = PDF_OUTPUT_DIR / file_name

    styles = _build_styles()

    document = SimpleDocTemplate(
        str(output_path),
        pagesize=A4,
        rightMargin=20 * mm,
        leftMargin=20 * mm,
        topMargin=20 * mm,
        bottomMargin=20 * mm,
        title=documentation.project_title,
        author="Idea Visualizer AI",
    )

    story = []

    # Document title.
    story.append(
        Paragraph(
            documentation.project_title,
            styles["title"],
        )
    )

    story.append(
        Paragraph(
            "Generated by Idea Visualizer AI",
            styles["subtitle"],
        )
    )

    # Project overview.
    story.append(
        Paragraph(
            "Project Overview",
            styles["heading"],
        )
    )

    story.append(
        Paragraph(
            documentation.project_overview,
            styles["body"],
        )
    )

    # Requirements.
    _add_section(
        story,
        "Client Requirements",
        documentation.client_requirements,
        styles,
    )

    # Target audience.
    _add_section(
        story,
        "Target Audience",
        documentation.target_audience,
        styles,
    )

    # Pages.
    _add_section(
        story,
        "Pages",
        documentation.pages,
        styles,
    )

    # Features.
    _add_section(
        story,
        "Features",
        documentation.features,
        styles,
    )

    # Website structure.
    _add_section(
        story,
        "Website Structure",
        documentation.website_structure,
        styles,
    )

    # Design decisions.
    _add_section(
        story,
        "Design Decisions",
        documentation.design_decisions,
        styles,
    )

    # Technology.
    _add_section(
        story,
        "Technology Used",
        documentation.technology_used,
        styles,
    )

    # Responsive behavior.
    _add_section(
        story,
        "Responsive Behavior",
        documentation.responsive_behavior,
        styles,
    )

    # Accessibility.
    _add_section(
        story,
        "Accessibility Features",
        documentation.accessibility_features,
        styles,
    )

    # Validation.
    _add_section(
        story,
        "Validation Summary",
        documentation.validation_summary,
        styles,
    )

    # Repairs.
    _add_section(
        story,
        "Repair Summary",
        documentation.repair_summary,
        styles,
    )

    # Final summary.
    story.append(
        Paragraph(
            "Final Summary",
            styles["heading"],
        )
    )

    story.append(
        Paragraph(
            documentation.final_summary,
            styles["body"],
        )
    )

    # Generate PDF.
    document.build(story)

    return output_path