from app.schemas.documentation import DocumentationSpecification
from app.schemas.generation import (
    DesignSpecification,
    RepairSpecification,
    ValidationSpecification,
    WebsiteSpecification,
)
from app.services.llm_service import client, MODEL_NAME


async def generate_documentation(
    website_specification: WebsiteSpecification,
    design_specification: DesignSpecification,
    validation_specification: ValidationSpecification,
    repair_specification: RepairSpecification | None,
) -> DocumentationSpecification:
    """
    Generate structured client-facing documentation for the final
    generated website.

    The Documentation Agent uses the website requirements, UI/UX design,
    validation result, and repair history to create accurate documentation
    that can later be converted into a professional PDF.
    """

    if website_specification is None:
        raise ValueError("Website specification is required.")

    if design_specification is None:
        raise ValueError("Design specification is required.")

    if validation_specification is None:
        raise ValueError("Validation specification is required.")

    repair_information = (
        repair_specification.model_dump_json(indent=2)
        if repair_specification is not None
        else "No repairs were required."
    )

    input_data = (
        "WEBSITE REQUIREMENTS:\n"
        f"{website_specification.model_dump_json(indent=2)}\n\n"
        "UI/UX DESIGN SPECIFICATION:\n"
        f"{design_specification.model_dump_json(indent=2)}\n\n"
        "VALIDATION RESULT:\n"
        f"{validation_specification.model_dump_json(indent=2)}\n\n"
        "REPAIR INFORMATION:\n"
        f"{repair_information}"
    )

    response = await client.responses.parse(
        model=MODEL_NAME,
        instructions=(
            "You are a senior technical documentation specialist. "
            "Create professional client-facing documentation for the "
            "final website generated by an AI website prototyping platform. "
            "\n\n"
            "Use only the information provided in the project data. "
            "Do not invent pages, features, technologies, or functionality "
            "that were not requested or implemented. "
            "\n\n"
            "The documentation should clearly describe the completed "
            "website and contain the following information: "
            "project title, project overview, client requirements, "
            "target audience, pages, features, website structure, "
            "design decisions, technologies used, responsive behavior, "
            "accessibility features, validation results, repair summary, "
            "and final project summary. "
            "\n\n"
            "Write the content professionally because the structured "
            "result will later be converted into a client-facing PDF."
        ),
        input=input_data,
        text_format=DocumentationSpecification,
    )

    if response.output_parsed is None:
        raise RuntimeError(
            "The AI model did not return a valid documentation specification."
        )

    return response.output_parsed